---
title: "concept-reddit-data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(dplyr) # tools for data wrangling in R
library(reticulate) # provides a comprehensive set of tools for interoperability 
                    # between Python and R.
```
```{r configure python}
# R code chunk
# configure Python
reticulate::py_config() # Double check that reticulate is actually using a 
                        # new conda environment.
reticulate::py_install("sklearn", pip = TRUE) # force install with pip. sklearn
                                              # wasn't coming up via anaconda.
reticulate::py_install("matplotlib")
reticulate::py_install("keras")
reticulate::py_install("pandas")
reticulate::py_install("requests")


# setting up the Python environment and bringing in the required Python packages 
# is important.
# Running this code will take about 5 to 10 minutes if these Python libraries
# are not already installed.

# Common trouble shooting:
# if missing a package, try adding its name in an additional argument of 
# py_install. if py_install isn't working then try adding the pip = TRUE
# argument to try installing the library through pip rather than anaconda.
```


```{python}
# Python code chunk

# import required Python packages
import numpy as np
import numpy as np
import matplotlib.pyplot as plt
# import keras
import pandas as pd
import requests

```


```{python}


 
subreddit = 'python'
limit = 100
timeframe = 'month' #hour, day, week, month, year, all
listing = 'top' # controversial, best, hot, new, random, rising, top
 
def get_reddit(subreddit,listing,limit,timeframe):
    try:
        base_url = f'https://www.reddit.com/r/{subreddit}/{listing}.json?limit={limit}&t={timeframe}'
        request = requests.get(base_url, headers = {'User-agent': 'yourbot'})
    except:
        print('An Error Occured')
    return request.json()
 
r = get_reddit(subreddit,listing,limit,timeframe)

```

```{python}

def get_post_titles(r):
    '''
    Get a List of post titles
    '''
    posts = []
    for post in r['data']['children']:
        x = post['data']['title']
        posts.append(x)
    return posts
 
posts = get_post_titles(r)
print(posts)

```